apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - image: host.docker.internal:5001/echo-server:v1.0.0
          name: echo-server
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
